# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18dc05eac38f6178417c6d3c999a358fdbff9edbad1352541813d2015fd77ea95ccfdc5bf560777c4e3ff71e9d6a26c27295eba0fd0a0e70dfa82dabd7444bdf

test:
  secret_key_base: 623eef790611ab06f391eccade31576779d2629ff0c5c7f32de98ae47e7511fb7534d8a9ad667df0f3b6528cad72c2f6e7bbefcdb4935869ccbb46c38e3db506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
